# Site settings
title: WBUVE
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Weibo UVE RD Team
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wbuve.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wbuve

# Build settings
markdown: kramdown
